name: test
on:
  push:
    branches:
      - 'main'
jobs:
  build:
    name: Build
    runs-on: self-runner-node
    steps:
      - name: "Trigger jenkins job"
        uses: 'Others/Pipeline-example@main' 
        with:
          jenkins-url: 'http://localhost:8080/'
          job-name: 'Pipeline-example'
